### ISSUE TITLE
Optimize initialization

### ISSUE THREAD

**Issue by armanbilge** [typelevel/idna4s#21]
Some ideas for `BitSet` optimizations in:
- https://github.com/typelevel/cats-collections/pull/548#discussion_r980373416

I bet there's other various low-hanging fruit.

The performance benchmarks suggest to me that we've definitely hit on the right data structures, ideally we can just build them up a little bit faster :)

**Comment by isomarcte** [comment]
I believe we've got this changed over everywhere, so I'm going to close it.

**Comment by armanbilge** [comment]
I think my goal for this issue was to point out there are still more optimizations we can do. The cats-collections PR comment I linked to suggested one such, yet-to-be-implemented optimization.
