### ISSUE TITLE
v0.0.1

### ISSUE THREAD

**Issue by armanbilge** [typelevel/idna4s#8]
@isomarcte how would you feel about publishing a v0.0.1 (or v0.1.0) with what's currently on `main`? So we can use your Punycode implementation just as a holdover for Scala Native in https://github.com/Comcast/ip4s/pull/427. Since both the Native stuff and this library are pretty new I wouldn't worry about it forcing us to lock down the binary API prematurely; we can just break if we need to.

Thanks!

**Comment by isomarcte** [comment]
@armanbilge I'm fine with that. The interface _will_ change, but hopefully not too much.

FYI, I'm driving cross country for the next few days, so my responses will have higher latency.

**Comment by armanbilge** [comment]
Thanks. Have a safe drive!

**Comment by armanbilge** [comment]
https://github.com/typelevel/idna4s/releases/tag/v0.0.1
